### ISSUE TITLE
Crash at SecureCredentialsManager line 273 [SDK-1953]

### ISSUE THREAD

**Issue by stephen1706** [auth0/Auth0.Android#334] opened 2020-09-07 06:05 UTC
### Description

I have found a few crashes at Crashyltics at `SecureCredentialsManager` class, I am not clear how to reproduce this as well, but basically it happened when trying to refresh the access token

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String aer.e()' on a null object reference
com.auth0.android.authentication.storage.SecureCredentialsManager$1.onSuccess (SecureCredentialsManager.java:273)
com.auth0.android.authentication.storage.SecureCredentialsManager$1.onSuccess (SecureCredentialsManager.java:269)
com.auth0.android.request.internal.BaseRequest.postOnSuccess (BaseRequest.java:93)
com.auth0.android.request.internal.SimpleRequest.onResponse (SimpleRequest.java:77)
com.newrelic.agent.android.instrumentation.okhttp2.CallbackExtension.onResponse (CallbackExtension.java:40)
com.squareup.okhttp.Call$AsyncCall.execute (Call.java:177)
com.squareup.okhttp.internal.NamedRunnable.run (NamedRunnable.java:33)
```

### Environment

- **Version of this library used: 1.23.0**
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser): Various OS and various device type**
- **Other modules/plugins/libraries that might be involved:**

**Comment by lbalmaceda** [comment] 2020-09-07 14:52
hi @stephen1706 👋  [Line 273](https://github.com/auth0/Auth0.Android/blob/1.23.0/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L273) (in 1.23.0) points to the use of [TextUtils#isEmpty](https://developer.android.com/reference/android/text/TextUtils#isEmpty(java.lang.CharSequence)) which is correctly handling null values. So the only possibility of a NPE is when the `fresh` or `credentials` values are null. 
- `fresh` shouldn't be null as was just received from the server on that same callback. 
- `credentials` on the other hand, I guess it could be null if the stored data was somehow corrupted in between the check of its existence and the value retrieval. It's hard to tell because the call is on the same line. However, I'd expect the JSON deserialization to fail in that case.

It might be an isolated case, I recommend you update to the latest version of this SDK and see if the problem is fixed there. Please, read the changelog notes in case you do migrate, to ensure you're handling the errors returned by the callback https://github.com/auth0/Auth0.Android/blob/master/CHANGELOG.md#1240-2020-07-16.

If this problem persists, I'd need more information that can help me reproduce the issue.

**Comment by stephen1706** [comment] 2020-09-08 05:10
Hi @lbalmaceda, thanks for the reply. If I check the implementation, I can see at line 262, it is already calling `credentials.getRefreshToken()`, had this been problematic, it'd crash at this line instead.
https://github.com/auth0/Auth0.Android/blob/deeaa71f2afa3de2b69c93aedd49183db5b60e7b/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L262

**Comment by lbalmaceda** [comment] 2020-09-08 12:53
That's correct, I missed that and this one as well. https://github.com/auth0/Auth0.Android/blob/1.23.0/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.java#L252

I'll close this but if you run into trouble again, we can reopen and investigate.

**Comment by stephen1706** [comment] 2020-09-11 04:43
Hi @lbalmaceda , it is still happening at our users as the crash is still happening at Crashlytics, however I am unable to reproduce it here. That would mean the `fresh` object is returning null? Is there any case when this will happened?

**Comment by lbalmaceda** [comment] 2020-09-11 10:19
@stephen1706 Can you double check in crashlytics which version of this library those builds were using?

**Comment by stephen1706** [comment] 2020-09-11 10:24
@lbalmaceda we're using version 1.23.0 and never changed the version yet

**Comment by lbalmaceda** [comment] 2020-09-11 10:50
Ok, no worries I'll try to repro. Could you share the snippet you use to sign in the first time (I want to check the params) and also the line where you obtain the credentials from this manager (here I want to see the scope). Thanks. 

I'll add this to our backlog and bring it up on the next planning.

**Comment by stephen1706** [comment] 2020-09-14 04:52
@lbalmaceda  during login : 
```
  WebAuthProvider.login(auth0)
                .withParameters(parameters)
                .withScheme(activity.getString(R.string.alias_auth0_scheme))
                .withScope("openid offline_access profile email update:my_profile read:my_profile update:my_email")
                .withAudience(configuration.aliasApiAudience)
                .start(activity, object : AuthCallback {...}
```
And to retrieve the credentials I just use
```secureCredentialsManager.getCredentials(...)```

**Comment by lbalmaceda** [comment] 2020-09-14 19:24
Thanks @stephen1706 . We're tracking this internally under `SDK-1953`. I'll try to reproduce it and check-in back with you.

**Comment by lbalmaceda** [comment] 2020-10-30 13:45
Apologies for the time it took to try this on my side. 
I set up the Auth0 API to issue access tokens that last 60 seconds. I logged in from the mobile app, using the SDK on version 1.23.0. Then stored those received tokens in the SecureCredentialsManager. A minute after that, I closed the app and re-opened it. That triggered a `getCredentials()` on the manager instance. I set up a breakpoint to check if it was going to renew the credentials or not, and indeed since they've expired, they were renewed. The request succeeded, without NPE being thrown at any point. I was not able to reproduce this. Unless we find a clear way to reproduce the issue, is really hard to debug and find the cause of the error you are facing. I'll leave this open for one more week in case anyone can come up with alternative repro steps.

**Comment by CrispBull** [comment] 2020-12-02 17:13
I am also having this issue. It's very random, sometimes it works, other times it fails, causing us to log users out a lot of times (very very frustrating). Here's the log we get
```
Non-fatal Exception: com.auth0.android.authentication.storage.CredentialsManagerException
An error occurred while trying to use the Refresh Token to renew the Credentials.
com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure (SecureCredentialsManager.java:302)
com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure (SecureCredentialsManager.java:288)
com.auth0.android.request.internal.BaseRequest.postOnFailure (BaseRequest.java:98)
com.auth0.android.request.internal.SimpleRequest.onResponse (SimpleRequest.java:72)
com.squareup.okhttp.Call$AsyncCall.execute (Call.java:177)
com.squareup.okhttp.internal.NamedRunnable.run (NamedRunnable.java:33)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.lang.Thread.run (Thread.java:764)
Caused by com.auth0.android.authentication.AuthenticationException
An error occurred when trying to authenticate with the server.
com.auth0.android.request.internal.AuthenticationErrorBuilder.from (AuthenticationErrorBuilder.java:29)
com.auth0.android.request.internal.AuthenticationErrorBuilder.from (AuthenticationErrorBuilder.java:12)
com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse (BaseRequest.java:139)
com.auth0.android.request.internal.SimpleRequest.onResponse (SimpleRequest.java:72)
com.squareup.okhttp.Call$AsyncCall.execute (Call.java:177)
com.squareup.okhttp.internal.NamedRunnable.run (NamedRunnable.java:33)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
```

Like I said, sometimes this call to refresh token is successful, many other times it fails. This is the number cause of bad experience for our users. Let me know if there's any way I can help track and resolve this issue.

**Comment by lbalmaceda** [comment] 2020-12-02 18:13
@CrispBull no, that stack is not the same issue that's being discussed here. The error you posted seems to relate to some dashboard configuration issue or maybe an invalid refresh token being sent (e.g. expired). But given that networking logging is disabled by default, I cannot tell without knowing the code and description sent by the server. If you are using refresh token rotation make sure you handle the synchronism as the credentials manager class doesn't, and consecutive requests to refresh the same refresh token will fail.

**Comment by CrispBull** [comment] 2020-12-03 19:07
Thanks for your response @lbalmaceda, can you please clarify what you mean by this **"If you are using refresh token rotation make sure you handle the synchronism as the credentials manager class doesn't, and consecutive requests to refresh the same refresh token will fail."**

**Comment by lbalmaceda** [comment] 2020-12-03 19:25
RTR is an optional feature that you could have enabled in your client for added security. When that's enabled, once a refresh token is exchanged for a new pair of tokens, you will receive a new refresh token (that you should save) and the old one will be deactivated. If you issue two (or more) requests **at the same time** exchanging the same refresh token, one call will succeed and invalidate the used refresh token, and the remaining requests will fail because they sent the now invalidated refresh token.

What's explained here basically https://auth0.com/docs/tokens/refresh-tokens/refresh-token-rotation#automatic-reuse-detection.

**Comment by CrispBull** [comment] 2020-12-08 08:46
I am still getting this issue even after saving the credentials in the `SecureStorageManager` after logging in. Here's my log after enabling logging on the app. 

```
ontent-Type: application/json; charset=utf-8
    Content-Length: 186
    Accept-Language: en_US
    Auth0-Client: ...
D/OkHttp: {"refresh_token":"v1....-...I","grant_type":"refresh_token","client_id":"..."}
    --> END POST (186-byte body)
D/OkHttp: <-- HTTP/1.1 403 Forbidden (1015ms)
    Date: Tue, 08 Dec 2020 08:13:20 GMT
D/OkHttp: Content-Type: application/json
    Transfer-Encoding: chunked
    Connection: keep-alive
    Set-Cookie: ...; expires=Thu, 07-Jan-21 08:13:20 GMT; path=/; domain=....; HttpOnly; SameSite=Lax; Secure
    CF-Ray: 5fe506c8eb04c4fc-LOS
   D/OkHttp: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  ... Max-Age=31557600; Path=/; Expires=Wed, 08 Dec 2021 14:13:20 GMT; HttpOnly; Secure; SameSite=None
    Path=/; Expires=Wed, 08 Dec 2021 14:13:20 GMT; HttpOnly; Secure
    Set-Cookie:..E=; path=/; expires=Tue, 08-Dec-20 08:43:20 GMT; domain=.eu.auth0.com; HttpOnly; Secure; SameSite=None
D/OkHttp: {"error":"invalid_grant","error_description":"Unknown or invalid refresh token."}
D/OkHttp: <-- END HTTP (81-byte body)
D/SecureCredentialsManager: Credentials have expired. Renewing them now...
...
/OkHttp: Set-Cookie: __cf_bm=...8A=; path=/; expires=Tue, 08-Dec-20 08:43:21 GMT; domain=.eu.auth0.com; HttpOnly; Secure; SameSite=None
    Server: cloudflare
...
D/OkHttp: {"error":"invalid_grant","error_description":"Unknown or invalid refresh token."}
E/LoggingTracker: logging caught exception
    com.auth0.android.authentication.storage.CredentialsManagerException: An error occurred while trying to use the Refresh Token to renew the Credentials.
        at com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure(SecureCredentialsManager.java:340)
        at com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure(SecureCredentialsManager.java:317)
        at com.auth0.android.request.internal.BaseRequest.postOnFailure(BaseRequest.java:98)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:72)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:29)
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:12)
        at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:139)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:72) 
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

 com.auth0.android.authentication.storage.CredentialsManagerException: An error occurred while trying to use the Refresh Token to renew the Credentials.
        at com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure(SecureCredentialsManager.java:340)
        at com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure(SecureCredentialsManager.java:317)
        at com.auth0.android.request.internal.BaseRequest.postOnFailure(BaseRequest.java:98)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:72)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:29)
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:12)
        at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:139)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:72) 
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
    com.auth0.android.authentication.storage.CredentialsManagerException: An error occurred while trying to use the Refresh Token to renew the Credentials.
        at com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure(SecureCredentialsManager.java:340)
        at com.auth0.android.authentication.storage.SecureCredentialsManager$1.onFailure(SecureCredentialsManager.java:317)
        at com.auth0.android.request.internal.BaseRequest.postOnFailure(BaseRequest.java:98)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:72)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:29)
        at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:12)
        at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:139)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:72) 
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

**Comment by lbalmaceda** [comment] 2021-03-11 10:17
@stephen1706 Closing this due to not being able to reproduce on this side. 

With regards to what you've reported @CrispBull, if you find the endpoint and payload that triggered this, please create a new issue with the reproduction steps so we can triage. Thanks

**Closed by lbalmaceda** 2021-03-11 10:17 UTC
Labels: waiting for customer
