### ISSUE TITLE
Force refresh access-token

### ISSUE THREAD

**Issue by skjolber** [auth0/Auth0.Android#614] opened 2022-10-26 10:57 UTC
### Describe the problem you'd like to have solved

We have some time-sensitive operations in our app. So before entering into those operations, it would have been nice to programmatically obtain an access-token with as long as possible time left before expiry. Then we would have less login screens and extra refresh call delays.

The current support for the ttl parameter in `SecureCredentialsManager` does not sufficiently cover our needs, because a (hardcoded) value would be hampered by time-to-live configuration changes on the server side. 

Say we begin with an access-token two-hour duration, pass in a 1:55 ttl in your SDK. Then deploy the apps, and then add some sensitive data which make us want the duration to be one hour instead. Then 1:55 would start throwing an exception in the already deployed apps. 

### Describe the ideal solution
Expose the total time to live for the access-token and also let us force an access-token update.

## Alternatives and current work-arounds
Somehow calculate the time to live using access-token fields.

**Comment by poovamraj** [comment] 2022-10-28 14:41
Hi @skjolber, it is by design that we avoid providing a force refresh method as you can see in this discussion which is very similar to your use case - https://github.com/auth0/Auth0.swift/pull/395

The improper use of the suggested method could lead to developers running into rate limiting and other issues. Can the TTL be provided in a dynamic way through the server? 

Regarding the other query
> Expose the total time to live for the access-token

You can use this property `expiresAt` from the `Credentials` object to get that information

**Comment by skjolber** [comment] 2022-10-28 21:22
> You can use this property expiresAt from the Credentials object to get that information

I do not understand, please provide an example.

> The improper use of the suggested method could lead to developers running into rate limiting and other issues. 

What are those other issues? The improper use of the current API surely could lead to rate limiting already / why would there be improper use?

**Comment by poovamraj** [comment] 2022-11-06 21:32
@skjolber the chances of someone giving a very high minTTL would be very less compared to using a method in a wrong way to force a refresh token.

For example, currently `getCredentials` is used from different threads in different APIs simultaneously. There can be a similar scenario if we introduce this method as well. 

> Expose the total time to live for the access-token

By this you are mentioning the total time the Access Token is valid right? If so, you can use the `expiresAt` property which is part of the `Credentials` object returned from `getCredentials`

**Comment by skjolber** [comment] 2022-11-11 20:48
@poovamraj to be clear, I want the library to provide the total time to live, I do not want to somehow detect when a token is renewed and then save a reference time and then compare it to `expiresAt`. This value is also returned by the server in the "wrapper" which contains the access- and id-token. I would like the expiry time of the refresh token too, if (already?) possible.

The use-case for a forced refresh is clear. If you are worried about misunderstandings / misue, then I would argue that adding proper documentation and/or shipping it as a plugin to the default behaviour is the proper approach.

**Comment by poovamraj** [comment] 2022-12-05 13:53
@skjolber I understand the points raised, but the reason to be conscious about this is the possibilities such API design would open up. We haven't received other queries about the forced refresh of the access token

Using `minTTL` would cover the following scenarios correctly

- Unwanted refreshes can be avoided and we can follow the most efficient way of refreshing a token.
- This will force the developer to think of what would be the ideal TTL they would want for their access token
- In the context of where doing a refresh is not at all possible, the user can provide a large enough TTL to get the maximum possible life for an access token.

Regarding getting the total time to live for an access token, We do get the `expires_in` field from the server, but exposing this would mean we provide incorrect information to the user (i.e) Let's say a token was generated at 13:00 and has `expires_in` as 300. If the user access the token at 13.01 and checks the `expires_in` as 300, then it would mean the token is expiring at 13.06 instead of the correct time which is 13.05.

Hope this helps, you can let us know what you think about it or give us the scenario where using a large enough TTL to force refresh a token is not replaceable for a separate method.

**Comment by deepakUnnikrishnan12** [comment] 2022-12-07 22:32
Hey @poovamraj,
How can we handle a scenario in which the access token has expired and refresh token is present but is past its lifetime ?
In the current SDK, `SecureCredentialManager.hasValidCredentials()` returns true when a refreshToken (KEY_CAN_REFRESH) is present in store. If we use the refreshToken to renew, it fails. Is there a way to handle this ?

**Comment by skjolber** [comment] 2022-12-11 23:49
@poovamraj `minTTL` is **disfunctional** as it is currently implemented, because [it blows up if the requested ttl is higher than the ttl of the token returned by the authentication server](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L485) ([without saving](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L509) the updated token). So it can't be used as indicated in your third bullet point?

So essentially, for your third bullet point, developers wanting to change the ttl on the authorization server must first update ALL android apps to request a lower ttl. This can be quit a slow process. And something that looks like an innocent change on the authorization server can start crashing all clients. The clients will be likely to request a lot of tokens in this situation, when retrying network calls, which might trigger rate limiting and a world of hurt.

Your example of `expires_in` as 300, it would be quite acceptable to subtract the request time from from the 300 seconds, so that `misunderstanding` do not happen.

**Comment by poovamraj** [comment] 2023-01-25 06:57
Hi @skjolber I agree with you on this. Throwing an exception does restrict our ability to get a token with max limit. Considering that functionality, providing a forceRefresh paramater in our method would be the best way to go ahead.

We can add this to our backlog and prioritize it from there, but we can also guide you with going ahead with a PR if you would like to contribute.

**Comment by poovamraj** [comment] 2023-03-14 18:46
@skjolber we have created a PR for this feature here - https://github.com/auth0/Auth0.Android/pull/637

Please provide your feedback there as we found it very valuable when discussing this issue. We will close this issue now and track the conversation in the PR. Thanks again for this great feature request.

**Closed by poovamraj** 2023-03-14 18:46 UTC
Labels: feature request
