### ISSUE TITLE
Android R (Android 11) Issues

### ISSUE THREAD

**Issue by dsuresh-ap** [auth0/Auth0.Android#310] opened 2020-06-30 17:49 UTC
### Description

On the Android R (11) emulator, our Auth0 sign-on is not working. It works fine on all other older versions.

### Reproduction

1. Cleared all cookies, cache, browsing data from Chrome (emultator's default browser)
2. Fresh installed our app
3. Started Auth0 flow
4. Attempt to log into either Google or Microsoft.

See attached images of where the app gets stuck in a loading state.

![google](https://user-images.githubusercontent.com/21132682/86159526-7b25d280-bad8-11ea-9dcf-42614b863d07.png)
![microsoft](https://user-images.githubusercontent.com/21132682/86159528-7bbe6900-bad8-11ea-97e7-c0f3901baac4.png)

Once Google sign-in did get through and was able to redirect back into the app.
Also to note performing the same flow on Chrome directly works fine.

I found the following related logs for both Google and Microsoft sign-in. It looks like the redirection was attempted but we were never returned back to our app.
```
2020-06-30 13:38:20.522 557-857/? I/ActivityTaskManager: START u0 {dat=mobile://<url>/callback?code=CUxFImtjlT2FAvkM&state=JC7plPLpgKw1hr-GfDzI6Z323_k5hiUCq64OUXi2Cgg flg=0x24000000 cmp=<package>/com.auth0.android.provider.AuthenticationActivity} from uid 10150
```

This log is not there on other devices so not sure if this is related:
```
2020-06-30 13:42:15.234 11928-11928/? E/cr_InstantAppsHandlerI: Exception when calling getInstantAppLaunchData
    bs: 19500: Not an instant app
        at Ju.a(chromium-TrichromeChromeGoogle.aab-stable-410404481:3)
        at yv.a(chromium-TrichromeChromeGoogle.aab-stable-410404481:6)
        at com.google.android.gms.common.api.internal.BasePendingResult.k(chromium-TrichromeChromeGoogle.aab-stable-410404481:16)
        at com.google.android.gms.common.api.internal.BasePendingResult.j(chromium-TrichromeChromeGoogle.aab-stable-410404481:5)
        at sA.a1(chromium-TrichromeChromeGoogle.aab-stable-410404481:28)
        at oC.onTransact(chromium-TrichromeChromeGoogle.aab-stable-410404481:3)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
```

### Environment

- **Version of this library used:1.23.0**
- **Version of the platform or framework used, if applicable: Android R (11) Emulator**
- **Other relevant versions (language, server software, OS, browser): Chome 83.0.4103.44**
- **Other modules/plugins/libraries that might be involved:NA**

**Comment by lbalmaceda** [comment] 2020-06-30 17:59
Could it be a problem in the emulator image? Have you tried with another variant of Android 11?

That first log line seems to tell the `AuthenticationActivity` was launched, but for some reason, the result was ignored. This can happen if the user canceled the authentication by closing the browser tab (clicking the X) or killing your app that was awaiting the result in the background. In this last scenario, when the app is re-launched again, there's no state of that previous authentication request and the processing of the result is ignored.

Try to dig through the logs looking for signals of the OS killing your app, as in when the device runs low on RAM.

**Comment by dsuresh-ap** [comment] 2020-06-30 19:18
@lbalmaceda Thanks for the suggestion that the `AuthenticationActivity` was launched and you are right the result was ignored.

For some reason `AuthenticationActivity` was created, resumed like normal. However `onResume` was called again without a call to `onNewIntent` resulting in the `resultMissing` check to pass. Then `AuthenticationActivity` gets created again (from logging in with one of the providers, Google, Microsoft) and this time in an invalid state `intentLaunched == false && authenticationIntent.getExtras() == null` which results in the `AuthenticationActivity` to close.

I observed the double `onResume` with no new Intent happening randomly. Still trying to figure out what exactly causes it. Any ideas would be appreciated.

**Comment by lbalmaceda** [comment] 2020-06-30 19:45
I skipped this question because you mentioned it was working on other devices. But that's the behavior one would see if the launch mode of the activity is other than "singleTask". See [here](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/AndroidManifest.xml#L35) we set it to the right value. 

Are you overriding the activity definition in your manifest? Or, still possible that this current beta of Android 11 is breaking that.

**Comment by dsuresh-ap** [comment] 2020-06-30 21:01
@lbalmaceda We are not overriding the Activity definition.

I used the same app build on an Android 10 emulator and a Samsung S9 running Android 10 and the issue isn't there.

I was able to resolve the issue by adding a delay between when we do a force logout and performing `WebAuthProvider.login()` so there seems to be some issue (or change in Android 10) with having the force logout redirect and the `WebAuthProvider.login` happening back to back.

This is our current login flow:
1. User clicks login
2. Start a force logout by launching Custom Tabs with a redirect url
3. Our internal redirect activity listens for that redirect url and notifies the LoginActivity to start the Auth0 flow using `WebAuthProvider`
4. `AuthenticationActivity` is created and `onResume` is called
5. `AuthenticationActivity` launches the authentication intent
6. `AuthenticationActivity.onResume` is immediately called and since `authenticationIntent.getData()` is `null` it finishes the Activity with `RESULT_CANCELED`.

However at this point the CustomTab is still open with the Auth0 login page and if the user does login, it will start `AuthenticationActivity` again in an invalid state.

Not sure what is causing `onResume` to get called twice in a row for Android 11. Adding a delay between when LoginActivity resumes from force logout and when we start the Auth0 flow fixes the issue but not sure why. Any ideas?

**Comment by lbalmaceda** [comment] 2020-07-03 18:02
What's the reason you have to call logout immediately after the authentication is requested by your user? Sounds like a task you should do when the user logs out manually and not when they try to log in.

The logout on this library consumes the same callback URL as the login. So once redirected back from the logout page, the app will open and you will receive the success call in your logout callback. Maybe you are not waiting for this call success before launching the authentication?

**Comment by dsuresh-ap** [comment] 2020-07-06 13:45
@lbalmaceda The reason is because we want to force the user out of any logged in SSO session in the browser. The way our app works is that the user could get logged out without requesting logout.

We wait for the logout redirect to fire an intent back into our app which does happen and works. For some reason on Android 11, if I don't add a delay between when we get the `onNewIntent` for the logout and starting the authentication through Auth0 , the AuthenticationActivity's `onResume` gets called twice. I don't think this is an issue of the Auth0 library because it as to do with Intents and Activity lifecycle maybe on Android 11 but was wonder if any of you experienced this behavior.

Also is there a proper way to ensure the user is logged out before starting authentication?

**Comment by lbalmaceda** [comment] 2020-07-06 16:26
The logout story is a bit tricky because it depends on the identity provider's (e.g. Facebook) implementation of the logout functionality. 

If the user is already logged in in Auth0 and you don't call `/logout`, the session is there and any attempt to log them in would automatically take you back from the browser to your app, probably without any user interaction.

When you invoke the `/logout` endpoint in your auth0 tenant, the Auth0 session is cleared. This is **on the Auth0 side**, not on your identity provider. When you try to log in again with the same provider, is probable that it won't ask you for credentials since, on their side, the session is still valid. In this case, the behavior would look like this: your user is prompted to choose one provider in the Auth0 login page (e.g. Facebook), then redirecting to this identity provider's site for login, which would redirect immediately back to the Auth0 login page and then your app.

If you instead invoke the `/logout` endpoint passing as an additional query param `federated`, Auth0 would try to log the user out of the identity provider's side. e.g. clearing that identity provider's session. This is probably not the flow you'd want to perform for every login, as in reality you as "app X" shouldn't be logging the user out of "sites Y" you don't own.

Does that make sense?

When this becomes tricky is that there's a way to force request credentials at login-time in the identity provider's side without having to clear that session in advance. And here is where every identity provider implements it differently. You'd have to google what param you need to send in that `/authorize` request in order to make it ask for credentials. Typically, you'd achieve that with the query param `prompt=login` but again, that is up to how the provider decides to implement it.

**Comment by dsuresh-ap** [comment] 2020-07-07 18:26
@lbalmaceda The flow we want is when the user starts the auth flow we always want the user to be brought to the selection screen where the user can choose between different providers.
Ex: User Starts flow -> List of different login providers ->
    If they are logged into that provider return back to app
    else allow the user to enter their provider's credentials then return back to app
Hence that is why we call `/logout` and wait for a redirect, to ensure that the user is brought to the login provider selection. Or as you said clear the Auth0 session on the Auth0 tenant.

This is all we want and it is working on < Android 11. The problem seems like its related to Intents. I was digging through the libraries docs and found: `WebAuthProvider.logout(account)`. Currently we are constructing the url on our own and listening to the intent ourselves. Does `WebAuthProvider.logout(account)` provide the same functionality as constructing the url on our own?

**Comment by dsuresh-ap** [comment] 2020-07-07 20:32
I changed our code to use `WebAuthProvider.logout(account)` and the issue is still there on Android 11.
This is what we do now:
```
WebAuthProvider.logout(createAuth0())
            .withReturnToUrl(<url>)
            .start(activity, object : VoidCallback {
                override fun onSuccess(payload: Void?) {
                    createSecureCredentialsManager(activity.applicationContext, createAuth0()).clearCredentials()

                    mainThread.post {
                        WebAuthProvider.login(createAuth0())
                                .withScheme(auth0Config.getScheme())
                                .withScope(SCOPE)
                                .withAudience(AUDIENCE)
                                .start(activity, object : AuthCallback { ... })
                    }
                }

                override fun onFailure(exception: Auth0Exception?) {
                              // Log
                }
            })
```

The `AuthenticationActivity` for login is getting finished because of `resultMissing` prematurely in Android 11. I think there might be some race-condition or changes to life-cycle in Android 11 causing this.

The only workaround I see to get it to work is to do: `mainThread.postDelayed(..., 500)`

Attached logs if it can help. 
[auth0_activity_logs.txt](https://github.com/auth0/Auth0.Android/files/4887028/auth0_activity_logs.txt)

**Comment by lbalmaceda** [comment] 2020-07-07 22:21
I suspect the issue is near that `mainThread.post` line. The callback blocks run on the main thread. You don't need to tell that explicitly. Remove that wrapping and see if that fixes it.
The alternative here is sending that prompt=login parameter I told you on my previous comment. You'd add that in the `WebAuthProvider.login` builder, before launching the authentication. That should force request the credentials, even if a session exists in Auth0, without you having to log out the user first.

**Comment by dsuresh-ap** [comment] 2020-07-08 14:47
Without the handler it looks like `AuthenticationActivity` gets started twice. Our force logout starts it and when `AuthenticationActivity` delivers the result on `onResume`, our callback starts it again for login. This is probably why we are seeing the issue in Android 11 in the first place.

Our app prompts logout -> AuthenticationActivity starts, resumes and launches the auth intent -> RedirectActivity launches intent for AuthenticationActivity -> AuthenticationActivity delivers the result -> the result goes into the callback which launches. `AuthenticationActivity` again for login. However at this point AuthenticationActivity did not finish itself so its resumed again in an improper state and finishes itself with canceled result. This is why the delay works around the issue for Android 11. It allows the AuthenticationActivity to finish itself after the result is delivered so a new instance can get started again after the delay.

Does that make sense? I am not sure if that is an issue or its just how its designed and will be.

With your other suggestion:
The `prompt=login` partially has the behavior we want. We want the user to be logged out of the Auth0 session but remain logged into any provider (google, microsoft, etc) however passing `prompt=login` logs out of the Auth0 session (good) but also logs them out of the provider. Not sure if that's just how our service is setup to handle that parameter.

**Comment by dsuresh-ap** [comment] 2020-07-09 18:13
If you see no issues with the implementation you can close this issue. We have decided to goa head and use `prompt=login` and remove the force logout logic we had before.

**Comment by lbalmaceda** [comment] 2020-07-13 19:51
It might be an issue of the Android 11 beta. But I'd wait until this is stable before testing with it.
Regarding the prompt param, remember I mentioned most of the identity providers (such as google or facebook) have different implementations of these flows. What Auth0 does is ignoring the session and prompting again for authentication. Providers like google might remember the "email" and only prompt for password, for example. But in the end, the "how to authenticate" is handed over to them. Auth0 will then receive the tokens and hand them back to you in the app. Nothing we can do here as well.
I'll close it and when Android 11 goes stable we can revisit.

**Closed by lbalmaceda** 2020-07-13 19:51 UTC
