### ISSUE TITLE
Crash when Auth0 is attempting to decrypt credentials

### ISSUE THREAD

**Issue by alexandrudumbravan-nutmeg** [auth0/Auth0.Android#592] opened 2022-07-07 14:23 UTC
### Describe the problem

We seem to be receiving a crash when trying to access the saved credentials on the device

Fatal Exception: android.security.keystore.KeyStoreConnectException: Failed to communicate with keystore service
       at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:256)
       at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:109)
       at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2984)
       at javax.crypto.Cipher.tryCombinations(Cipher.java:2891)
       at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
       at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
       at javax.crypto.Cipher.init(Cipher.java:1143)
       at javax.crypto.Cipher.init(Cipher.java:1084)
       at com.auth0.android.authentication.storage.CryptoUtil.RSADecrypt(CryptoUtil.java:271)
       at com.auth0.android.authentication.storage.CryptoUtil.getAESKey(CryptoUtil.java:369)
       at com.auth0.android.authentication.storage.CryptoUtil.decrypt(CryptoUtil.java:413)
       at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials$lambda-2(SecureCredentialsManager.java:331)
       at com.auth0.android.authentication.storage.SecureCredentialsManager$$InternalSyntheticLambda$0$c09ebe59feb1659569cade6fd369c5089a7c5416c6136c04dd1d923283ecba7f$0.run(SecureCredentialsManager.java:5)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)

### What was the expected behavior?

The credentials should either be retrieved or the error should be handled 

### Reproduction
The issue seems to happen sporadically and we currently aren't aware of any steps to reproduce the issue

### Environment

- **Version of this library used:** 2.7.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:** Devices observed: Huawei P30 and Huawei Mate 20 Pro with Android 10

**Comment by poovamraj** [comment] 2022-07-25 12:14
Hi @alexandrudumbravan-nutmeg This seems to be peculiar issue that I am not able to reproduce. Probably because I don't have Huawei devices to check this.

This looks like a known bug reported [here](https://issuetracker.google.com/issues/147384380) caused by an interrupted thread. Can you share a sample code on how you are invoking this function?

**Comment by alexandrudumbravan-nutmeg** [comment] 2022-07-26 15:05
Hello. 

We are just trying to get the stored credentials, however we are using RxJava and putting the result in a stream like in the example below. It's possible that disposing the stream might interrupt the thread, but I don't believe this to be the case.

`Observable.create<AuthTokenResponse> { emitter ->
                    getCredentials(object : Callback<Credentials, CredentialsManagerException> {
                        override fun onFailure(error: CredentialsManagerException) {
                            if (!emitter.isDisposed) {
                                emitter.tryOnError(authErrorHandler.handleCredentialsFailure(error))
                                emitter.onComplete()
                            }
                        }

                        override fun onSuccess(result: Credentials) {
                            if (!emitter.isDisposed) {
                                emitter.onNext(AuthTokenResponse(result.accessToken, result.refreshToken.orEmpty()))
                                emitter.onComplete()
                            }
                        }
                    })
                }`

**Comment by poovamraj** [comment] 2022-08-20 13:56
@alexandrudumbravan-nutmeg This looks like the bug report from Android I shared earlier and since it is already fixed, I don't think there would be a change required from our end. We are closing this for now but please feel to reopen if you have more doubts

**Closed by poovamraj** 2022-08-20 13:56 UTC
