### ISSUE TITLE
Gson TypeToken obfuscation issue

### ISSUE THREAD

**Issue by AlexDoesCode** [auth0/Auth0.Android#623] opened 2022-12-02 17:05 UTC
### Describe the problem

After updating `Gson`( to 2.10) and other major project versions like gradle(to 7.4), gradle plugin and Kotlin versions(to 1.7.21) etc. obfuscated builds report a crash when launching universal login flow with `WebAuthProvider.login()`

### What was the expected behavior?

ChromeCustomTab aka WebView with universal flow launches

### Reproduction

- Step 1 resolve Gson version clash using version 2.10 after updating kotlin and gradle versions
- Step 2 build obfuscated build flavor
- Step 3 launch universal login flow

### Environment

- **Version of this library used: 2.8.0**
- **Which framework are you using, if applicable: native Android**
- **Other modules/plugins/libraries that might be involved: Gson**
- **Any other relevant information you think would be useful:**

### **Log**
```
java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
       at com.google.gson.reflect.TypeToken.getTypeTokenTypeArgument(TypeToken.java:41)
       at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:2)
       at b15.<init>(GsonAdapter.kt:1)
       at qp.<init>(AuthenticationAPIClient.kt:5)
       at q07.<init>(OAuthManager.kt:45)
```

### **Workaround**
add the following to your proguard rules:
```
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
```

**Comment by poovamraj** [comment] 2023-01-03 14:49
Hi, @AlexDoesCode I tested this with the configuration you mentioned here - https://github.com/poovamraj/AndroidTest and I was not able to reproduce this. It would be great if you can make the issue reproduce in the above repo as it is just a boilerplate with Auth0 integration. This will help us determine whether the issue is in the SDK or the integrating application

In the meantime, we would like to close this issue as it doesn't have much community engagement and you have discovered a workaround for your application.

Feel free to reopen it if you want to continue more about this.

**Closed by poovamraj** 2023-01-03 14:49 UTC
