### ISSUE TITLE
AuthenticationException when renew fails

### ISSUE THREAD

**Issue by deepakUnnikrishnan12** [auth0/Auth0.Android#625] opened 2022-12-07 22:44 UTC
### Describe the problem

We are observing the below logs when calling `SecureCredentialsManager.awaitCredentials()` after `SecureCredentialsManager.hasValidCredentials()` returns true. This is observed when calling these functions after the refresh token might have expired. We do have Refresh Token rotation enabled.

```
An error occurred while trying to use the Refresh Token to renew the Credentials.\
                                                                            com.auth0.android.authentication.storage.CredentialsManagerException: An error occurred while trying to use the Refresh Token to renew the Credentials.\
                                                                            	at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials$lambda-3(SecureCredentialsManager.kt:513)\
                                                                            	at com.auth0.android.authentication.storage.SecureCredentialsManager.$r8$lambda$lzipqfeeDXjWZ6piYqZb9m3XmPs(Unknown Source:0)\
                                                                            	at com.auth0.android.authentication.storage.SecureCredentialsManager$$ExternalSyntheticLambda1.run(Unknown Source:10)\
                                                                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)\
                                                                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)\
                                                                            	at java.lang.Thread.run(Thread.java:1012)\
                                                                            Caused by: com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.\
                                                                            	at com.auth0.android.authentication.AuthenticationAPIClient$Companion$createErrorAdapter$1.fromJsonResponse(AuthenticationAPIClient.kt:810)\
                                                                            	at com.auth0.android.authentication.AuthenticationAPIClient$Companion$createErrorAdapter$1.fromJsonResponse(AuthenticationAPIClient.kt:795)\
                                                                            	at com.auth0.android.request.internal.BaseRequest.execute(BaseRequest.kt:144)\
                                                                            	at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials$lambda-3(SecureCredentialsManager.kt:479)\
                                                                            	at com.auth0.android.authentication.storage.SecureCredentialsManager.$r8$lambda$lzipqfeeDXjWZ6piYqZb9m3XmPs(Unknown Source:0)\'a0\
                                                                            	at com.auth0.android.authentication.storage.SecureCredentialsManager$$ExternalSyntheticLambda1.run(Unknown Source:10)\'a0\
                                                                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)\'a0\
                                                                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)\'a0\
                                                                            	at java.lang.Thread.run(Thread.java:1012)\'a0\
```

### Reproduction

Prerequisites:
Refresh token rotation is enabled.

1. Complete the authentication of the user and save credentials using `SecureCredentialsManager`.
2. Open the app after the refresh token's `token_lifetime` and call the `hasValidCredentials()` and then `awaitCredentials()` function.
3. `awaitCredentials()` function throws AuthenticationException.

### Environment

- **Version of this library used:** 2.8.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment] 2023-01-17 11:21
@deepakUnnikrishnan12 Looks like the Auth0 server is sending an error response. This should contain more detail. Can you share this?

**Comment by deepakUnnikrishnan12** [comment] 2023-01-17 15:01
Hey @poovamraj What other details are you looking for ?

**Comment by deepakUnnikrishnan12** [comment] 2023-01-17 15:18
@poovamraj If I debug into the `AuthenticationAPIClient`, I find the below for `values` variable inside the `fromJsonResponse` function.

"error" -> "invalid_grant"
"error_description" -> "Unknown or invalid refresh token."

**Comment by poovamraj** [comment] 2023-01-18 10:35
We are able to reproduce this. This is happening because our `hasValidCredentials` cannot check whether the refresh token is expired since this information is not returned from the server.

So we try to refresh the `access_token` but since the Refresh token is already expired we are getting invalid grant. With Refresh Token rotation enabled you cannot avoid its expiry.

The correct flow here is to ask the user to login again as their Refresh token has expired.

Does this help with your question?

**Comment by deepakUnnikrishnan12** [comment] 2023-01-18 14:51
@poovamraj Is there a way for the client apps integrating to identify such errors ?
In the current integration, when calling `SecureCredentialsManager#awaitCredentials()`, the SDK only throws `CredentialsManagerException`. There is no way for our app to identify such error codes.

**Comment by poovamraj** [comment] 2023-01-21 19:17
Hi @deepakUnnikrishnan12 we don't have a flag for this yet under `Auth0Exception` but feel free to add this and send a PR our way and we would be happy to merge it. Do let us know if you need any guidance on this and we would be happy to help.

**Comment by poovamraj** [comment] 2023-03-13 03:36
@deepakUnnikrishnan12 We now have a PR that implements this feature - https://github.com/auth0/Auth0.Android/pull/635. This should be merged and released soon. The progress of this issue can be tracked there so we will close this issue. Thanks for your feedback and feel free to reopen this issue if you have more doubts.

**Closed by poovamraj** 2023-03-13 03:36 UTC
Labels: question
