### ISSUE TITLE
An error occurred while trying to use the Refresh Token to renew the Credentials

### ISSUE THREAD

**Issue by zgordon02** [auth0/Auth0.Android#554] opened 2022-04-29 21:51 UTC
### Describe the problem

I am getting this exception when using the SecureCredentialsManager's `getCredentials` method: 

```
com.auth0.android.authentication.storage.CredentialsManagerException: An error occurred while trying to use the Refresh Token to renew the Credentials.
```

```
detailMessage: An error occurred when trying to authenticate with the server.
description: Unknown or invalid refresh token.
code: invalid_grant
```
However, right before calling this method, I called the `hasValidCredentials` method which returned true. I'm not sure if this is a bug or it I am misunderstanding, but are there valid scenarios where `hasValidCredentials` returns true but getCredentials can fail? Does anyone have any insight into what may be going on here?

Thanks in advance!

### Reproduction

- I called `credentialsManager.hasValidCredentials()` which returned true
- I then called `credentialsManager.getCredentials(credentialsReceivedCallback)` which threw the above exception

### Environment

- **Version of this library used:** 2.7.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment] 2022-05-02 07:45
Hi @zgordon02 👋 

You can refer to the [RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2) which describes this error as follows

> The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

The `hasValidCredentials` method just checks for the existence of `Credentials` locally. This doesn't include checking the credentials with the server. That is the reason even when `hasValidCredentials` returns true there is an error due to a change in the refresh token status.

**Comment by fpitters** [comment] 2022-05-04 15:12
We are investigating a similar issue.
We are not able to reproduce locally, but we see many reports with the same error `invalid_grant`, and we are trying to figure what conditions are producing it.

Please let us know if you have any hint on how we could investigate further.
For example, do you know if it's possible to get what particular option is producing the given error when refreshing the token: invalid, expired, revoked, not matching the redirection URI?

Thank you

**Comment by zgordon02** [comment] 2022-05-04 15:32
> We are investigating a similar issue. We are not able to reproduce locally, but we see many reports with the same error `invalid_grant`, and we are trying to figure what conditions are producing it.
> 
> Please let us know if you have any hint on how we could investigate further. For example, do you know if it's possible to get what particular option is producing the given error when refreshing the token: invalid, expired, revoked, not matching the redirection URI?
> 
> Thank you

It's likely that the refresh token is expired in these instances

**Comment by zgordon02** [comment] 2022-05-04 15:34
Is it possible that we add a check to the refresh token's expiration when we call `hasValidCredentials`?

**Comment by poovamraj** [comment] 2022-05-09 08:45
Hi @zgordon02, Since this doesn't seem to be an issue on the SDK side, we are closing this issue for now. Please feel to reopen this if you have any more questions on this. We will be happy to help

**Closed by poovamraj** 2022-05-09 08:45 UTC
Labels: waiting for customer
