### ISSUE TITLE
NullPointerException thrown when decrypting a token value that has been cleared

### ISSUE THREAD

**Issue by bennycao** [auth0/Auth0.Android#555] opened 2022-05-10 04:51 UTC
### Describe the problem
Since release 2.7.0 we are seeing a race condition whereby the credentials stored could be cleared just before retrieving the token to decrypt. This will throw the following.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
        at android.util.Base64.decode(Base64.java:118)
        at com.auth0.android.authentication.storage.SecureCredentialsManager.continueGetCredentials$lambda-2(SecureCredentialsManager.kt:328)
        at com.auth0.android.authentication.storage.SecureCredentialsManager.$r8$lambda$7G1WLYfu-nEy-0Emfjqpa7j0now(SecureCredentialsManager.kt)
        at com.auth0.android.authentication.storage.SecureCredentialsManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

### What was the expected behavior?
It is expected that the code would guard against trying to decrypt a token that has been cleared i.e encryptedEncoded is null here https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L328

### Reproduction

Below snippet is a convoluted example, but it shows how asynchronously the tokens can be updated/cleared and it is possible that by the time it reaches https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L328 . The token has been cleared and is null, and there is no guard when `Base64.decode` function is called.

```
            secureCredentialsManager.saveCredentials(myCredentials)
            GlobalScope.launch(Dispatchers.IO) {
                coroutineScope {
                    launch {
                        if (credentialsManager.hasValidCredentials(60L)) {
                            secureCredentialsManager.getCredentials(null, 60, callback)
                        }
                    }

                    launch {
                        secureCredentialsManager.clearCredentials()
                    }
                }
            }
```

This can be consistently reproduced.

### Environment

- **Version of this library used: 2.7.0**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved: No**
- **Any other relevant information you think would be useful:  Our code is written so that access to the SDK is via a single threaded context (making it thread safe), since the update to 2.7.0 with Thread Safe Change when calling `getCredentials` it switches threads and hence releasing the app to continue with execution asynchronously of other code. Maybe the thread safe code needs to cover `clearCredentials`, `hasValidCredentials` etc... ? or have a thread override to keep running in same thread...just thoughts **

**Comment by poovamraj** [comment] 2022-05-11 10:12
Hi @bennycao, I checked out this issue with the method you provided and the test case fails in both version 2.6.0 (without thread safe credential manager) and 2.7.0 (with thread safe credential manager). I also see that while `hasValidCredentials` is called using `credentialsManager` object, `getCredentials` is done using `secureCredentialsManager`. Is this a typo?

**Comment by bennycao** [comment] 2022-05-12 00:20
> Hi @bennycao, I checked out this issue with the method you provided and the test case fails in both version 2.6.0 (without thread safe credential manager) and 2.7.0 (with thread safe credential manager). I also see that while `hasValidCredentials` is called using `credentialsManager` object, `getCredentials` is done using `secureCredentialsManager`. Is this a typo?

Hi, thanks for your reply. Yes, agree it does fail in both 2.6.0 and 2.7.0. We mitigated the issue in 2.6.0 by running our own single thread context. Since 2.7.0 with the thread change of launching in another thread, this means we can continue work on our thread and this could mean we can `clear credentials`. This i believe should not be possible with thread safe change and clear is not thread safe ? Please let me know if i'm incorrect in this assumption.

Yes sorry, the `hasValidCredentials` should be  `secureCredentialsManager.hasValidCredentials()`  and is a typo in the snippet.

**Comment by bennycao** [comment] 2022-05-18 01:01
Hi @poovamraj , thanks for the reply.

I will try to explain a use case where we encounter this situation. 

Our app makes asynchronous api calls which require authentication. The number of calls varies but is possible that multiple (3-5) api calls are requested at the same time. Before making the http requests the auth tokens need to be added in the headers. This is when we call `getCredentials`.

In the event that the `refresh token` is `revoked` for whatever reason (e.g. security), and when a `renew token` is performed as part of `getCredentials` we catch the exception. As the token is now not useful we make the call to `clearCredentials` and essentially sign the user out. This is when we can encounter the NullPointerException as one process is trying to `getCredentials` and another has `clearCredentials`.

I hope this use case makes sense. Please let me know if there is anymore information you require.

Handling the NullPointerException would be great too.

**Comment by poovamraj** [comment] 2022-05-22 10:48
Hi @bennycao, we have noted this in our backlog and we will try to provide this fix by not affecting the backward compatibility for the developers. We are closing this issue for now. Please feel free to reopen it if you have more doubts.

**Comment by nicbell** [comment] 2022-05-27 18:04
I'm also experiencing this since upgrading. Looks like the thread safety changes actually did the opposite.

**Comment by willmetz** [comment] 2022-06-07 12:29
We are experiencing the same issue on our side as well, any updates on the priority of getting this fixed?

**Comment by poovamraj** [comment] 2022-06-20 14:29
@bennycao @nicbell @willmetz We have fixed this in this [PR](https://github.com/auth0/Auth0.Android/pull/576). We would really like for you to check this out and see whether it fixes the issue mentioned.

> I'm also experiencing this since upgrading

@nicbell As you can see in the thread we were able to see the issue even in previous versions, can you confirm this or provide more information on how this is happening only in the latest update?

**Comment by willmetz** [comment] 2022-06-20 20:05
thanks, I will give it a try in the next day here and let you know

**Comment by bennycao** [comment] 2022-06-22 00:58
@poovamraj is there an alpha release version i can pull down, or can i pull down this version for testing other than forking the code and building locally ?

**Comment by bennycao** [comment] 2022-06-22 06:15
@poovamraj I have tested the change and it will help prevent crashes.
Maybe as an improvement, could the SecureCredentialManager have a public constructor to accept an Executor to override the default ?

**Comment by willmetz** [comment] 2022-06-22 12:37
I am having issues reproducing the crash locally here, we are seeing a good amount of these crashes in production but reproducing it locally has been a challenge.  So I am not sure if testing the fix on a local build is going to be a ton of help here.

**Comment by poovamraj** [comment] 2022-06-22 12:48
@bennycao that is an interesting request. This should be possible but we want to keep it opinionated. Using a multi-thread executor could cause issues again. Can you explain why you want to customize this?

@willmetz I understand reproducing threading-related issues locally can be tricky. You can check out the mock provided by @bennycao to test this or we should be releasing the build with this fix soon and you can roll it out to your users slowly and check for the response?

**Comment by bennycao** [comment] 2022-06-23 08:48
@poovamraj just a thought. It would solve the issue in my usecase, but will cause issues if not used correctly.

**Comment by poovamraj** [comment] 2022-06-23 11:57
Great, we will close this issue for now. The changes should be reflected in the next release so keep an eye out for it. Thank you all for the contribution you have made and help in fixing this issue.

**Closed by poovamraj** 2022-06-23 11:57 UTC
Labels: waiting for customer
