### ISSUE TITLE
Null HashMap in AuthenticationException

### ISSUE THREAD

**Issue by carlyonj** [auth0/Auth0.Android#164] opened 2018-06-05 17:11 UTC
```
Fatal Exception: java.lang.NullPointerExceptionAttempt to invoke interface method 'int java.util.Map.size()' on a null object reference Raw Text
--
  | java.util.HashMap. (HashMap.java:253)
  | com.auth0.android.authentication.AuthenticationException. (SourceFile:76)
com.auth0.android.request.internal.AuthenticationErrorBuilder.from (SourceFile:23)
--
  | com.auth0.android.request.internal.AuthenticationErrorBuilder.from (SourceFile:9)
  | com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse (SourceFile:137)
  | com.auth0.android.request.internal.SimpleRequest.onResponse (SourceFile:68)
```

**Comment by lbalmaceda** [comment] 2018-06-05 17:27
version? request made?

**Comment by carlyonj** [comment] 2018-06-05 17:31
implementation 'com.auth0.android:auth0:1.12.2'

Unknown request, it's not in the crash log all I can see is from auth0. We do not instantiate any AuthenticationExceptions in our app though. All  we do is look for an exception to be of that type and then response to it if it is.

**Comment by lbalmaceda** [comment] 2018-06-05 17:42
But you are sharing a stacktrace that doesn't point to a line in our class. It says `SourceFile`. You need to translate it using your proguard output. Also, without knowing which was the expected and the actual response, there's not much we can do. At least we require the endpoint you were trying to call and which params you sent for that to happen.

**Comment by carlyonj** [comment] 2018-06-05 20:39
We aren't sure what was causing it, it seems likely that there was an issue with our backend that is no longer present.

It seems that the issue is that AuthenticationException is calling 

```
this.values = new HashMap<>(values);
```

with a null values object.

**Comment by spacemase** [comment] 2018-06-07 22:11
some Auth0 call that gets made (currently suspect UsersAPIClient::getProfile) makes a SimpleRequest and gets an unsuccessful response (return code outside 200-300). Auth0 tries to parse the response.body into a Map<String,Object> using gson. That parse attempt returns null and subsequently crashes when attempting to create AuthenticationException from ctor.

Can't yet determine which call is attempted from log, but guessing our Auth0 service is down as it is having availability issues.  The error handling during SimpleRequest attempts a naive gson parse of the Response.Body payload into a Map<String,Object> and assumes a Map is returned if not an Exception.  That does not appear to be sound, as we are seeing a null returned and subsequent usages of the payload mapping are not expecting null.

**Comment by spacemase** [comment] 2018-06-07 22:40
from the gson::fromJson docs:  

Returns:
an object of type T from the string. Returns null if json is null.

so for some as yet undetermined reason the Response.Body of the GET is null, so SimpleRequest crashes.

**Comment by sebastian-heinz** [comment] 2018-06-08 01:50
I had a similar issue a while back: https://github.com/auth0/Auth0.Android/issues/149
If it can be detected via status code outside of 200-300 maybe Auth0 could not try to parse the json to a map or other ways of preventing the app from crashing in case the response can not be parsed.

**Comment by spacemase** [comment] 2018-06-08 03:39
@sebastian-heinz I think this is the same issue!  In our case the status code is 503.  And we are calling UsersAPIClient::getProfile.

**Comment by lbalmaceda** [comment] 2018-06-08 17:51
Probably the same issue as pointed by @sebastian-heinz. But again, the server shouldn't have changed the response error since that would be a breaking change for all the users. Maybe it's a configuration error on your auth0 application or a Rule changing the response contents in an invalid way. Unless more details are provided I can't help you. **I just tried the `UsersAPIClient#getProfile()` method and it works as expected.** A valid and existing user ID game me the right user. A non-existing user ID gave me `inexisting_user` error code. An invalid user ID gave me a string format error. You might want to contact https://support.auth0.com for further help on your case. I'll close this until steps to reproduce the issue are added.

**Closed by lbalmaceda** 2018-06-08 17:51 UTC
