### ISSUE TITLE
AuthenticationAPIClient resetPassword connection not found

### ISSUE THREAD

**Issue by GabCast** [auth0/Auth0.Android#303] opened 2020-05-14 18:03 UTC
### Description

When using resetPassword fuction with AuthenticationAPIClient in Android SDK is always going for onFailureCallback with code: connection not found. We know our credentials ar fine because with the same config login or singUp function are working right.

We don't even see any activity on our dashboard.

### Reproduction

1. Request Login with AuthenticationAPIClient

```
        AuthenticationAPIClient(account)
                .resetPassword(emailId, CONNECTION)
                .start(authCallback)
```

2. Code: connection noy found

### Environment

Api: com.auth0.android:auth0:1.23.0
Android API28

**Comment by lbalmaceda** [comment] 2020-05-14 22:46
The error message states that the connection value that you are passing as the second parameter doesn't exist. According to the [endpoint docs](https://auth0.com/docs/api/authentication#change-password), it must be a valid Auth0 Database connection.

**Comment by GabCast** [comment] 2020-05-15 12:26
The thing is that the connection value is actually correct. We use the same config for other function and everything works correctly

**Comment by lbalmaceda** [comment] 2020-05-15 13:22
This is a dupe of https://github.com/auth0/Auth0.Android/issues/302. Let's keep the conversation there.

**Closed by lbalmaceda** 2020-05-15 13:22 UTC
Labels: waiting for customer
