### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by skjolber** [auth0/Auth0.Android#306] opened 2020-06-10 08:55 UTC
Migrate to AndroidX support libraries.

### Description
Android supprt libraries are out of date. Other libraries could be bumped as well.

### Reproduction
Harder to build updated application using old dependencies

### Environment
Android

**Comment by skjolber** [comment] 2020-06-24 12:10
So when are you planing on releasing it, and are 'those other changes' new features or regression fixes? Looks mostly like like there is no code changes so far, except from updated dependencies / imports.

**Comment by lbalmaceda** [comment] 2020-06-25 19:52
We don't have a public-facing issue/doc with what we plan next, neither a date of release. I've raised this with the team to discuss what's the best way to share our ideas and roadmap for the next major.

**Comment by colin-ifit** [comment] 2020-08-14 17:31
Now that it's been a few months, is there any idea of a release date?

**Comment by lbalmaceda** [comment] 2020-08-14 19:01
No decided date yet. I assume it will be brought up to work as part of the Q4 initiatives.

**Comment by scottyab** [comment] 2020-08-26 10:15
Hey @lbalmaceda - I appreciate you cannot give timeline for 2.0.0 and the switch to AndroidX - Just wanted to flag there's been a couple of recent Android articles talking about the saving in build time with dropping jetifier i.e https://adambennett.dev/2020/08/disabling-jetifier/ which flags this awesome plugin https://github.com/plnice/can-i-drop-jetifier

**Comment by lbalmaceda** [comment] 2020-08-26 20:56
@scottyab Thanks for sharing that. I'll make sure to raise more visibility of the AndroidX case.

**Comment by lbalmaceda** [comment] 2020-09-07 16:49
I'm labeling this issue to signal that the follow up is on our side now. There's no "investigation" to be done, we understand what the problem is. 👍

**Comment by scottyab** [comment] 2020-10-13 13:10
Hey @lbalmaceda was this issue added to the Q4 initiatives? Keen to understand if we're going to see a release so we can drop Jetifier by the end of the year. Thanks

**Comment by lbalmaceda** [comment] 2020-10-13 18:46
Hello, I appreciate the follow-up and apologize for the silence on this. 
I'm happy to report that in Q4, we're working on a new version of the Android SDK, which will be written on Kotlin. The next SDK will offer support for Android's latest version (API 30). It is important to note that there will be no usage of "support compat" libraries, as those will be coming through Android X dependencies now. Our current plan is to launch the new Android SDK by the end of Q4, potentially sooner.

**Comment by technoir42** [comment] 2020-10-13 23:19
What about those users who don't need new features? By tying AndroidX migration to a major release you are forcing us to adapt to the potential breaking changes just to get rid of support library. Ideally from the user's perspective migration of a library to AndroidX should be just a low-risk version bump and that's it.

**Comment by scottyab** [comment] 2020-10-19 10:48
Agree with @technoir42 moving to a full re-write adds additional risk and at the moment we are only looking to remove Jetifier. Totally open to move to v2 in time if there are features we need/want or support for the old SDK is dropped.  

I had a go at migrating to see how much effort it would be see PR #362 it was allot easier than last time I tried the migration wizard in Android Studio a year or so ago.  Let us know if this helps.

**Comment by technoir42** [comment] 2020-10-19 11:02
@lbalmaceda please consider releasing a 1.x-based version with AndroidX support without other breaking changes of 2.0.
If you really care about semver, you can do 2.0 as 1.x+AndroidX and then release new features in 3.0. Or you can just do it as a 1.x release.

**Comment by skjolber** [comment] 2020-10-19 11:08
@lbalmaceda as @technoir42 suggest, we want it too.

**Comment by lbalmaceda** [comment] 2020-10-21 09:41
Hello, as always, we appreciate the input and feedback. For this specific issue, Jetifier is the officially recommended way of using dependencies that have not migrated to AndroidX. Given this, we definitely understand the annoyance of the added build time Jetifier brings, which is not ideal. However, since we're currently in the middle of writing the next version of our Android SDK, our plan is to launch a single update later this quarter. The next version of our Android SDK will address this issue and a few other updates as well. We'll keep everyone updated as we get closer to launch. Thanks again, and we apologize for any inconvenience in the interim.

**Comment by japplin** [comment] 2020-11-03 21:32
What's the concern with just merging https://github.com/auth0/Auth0.Android/pull/362?

**Comment by latsson** [comment] 2021-01-11 13:52
Any update? No release happened in Q4 2020.

**Comment by VincentJoshuaET** [comment] 2021-01-15 03:23
This is the only library along with Lock that I need Jetifier for. Fortunately Google's standalone Jetifier command line tool works perfectly!

**Comment by VincentJoshuaET** [comment] 2021-01-19 06:26
> Any update? No release happened in Q4 2020.
https://github.com/auth0/Auth0.Android/commit/8d19e2a55c48506657eeb189ad4805f6ffbd4388

This happened but just a minor update.

**Comment by lbalmaceda** [comment] 2021-01-21 19:10
Thank you for your patience. We’ve exciting news to share with you!

Yesterday we published the first beta release of the v2 of this library. Please, visit the following issue to learn more about it. Thanks

#446

**Comment by lbalmaceda** [comment] 2021-02-11 19:52
Today we've released a new major version that includes this feature and allows the Jetifier plugin to be turned off. 

Please, don't hesitate to reach out with questions or feedback about this new version.
I'll close this now.

**Closed by lbalmaceda** 2021-02-11 19:52 UTC
Labels: feature request
