### ISSUE TITLE
Nullpointer when saving credentials

### ISSUE THREAD

**Issue by skjolber** [auth0/Auth0.Android#508] opened 2021-08-06 23:13 UTC
Seems there is a potential issue with the Pixel 2 emulator for level 27 in Firebase testlab. 

### Describe the problem

```
08-06 13:47:17.679: D/no.entur.abt.android.common.support.login.LoginActivity(9486): Successful login
08-06 13:47:17.685: D/no.entur.abt.android.common.support.login.UserCoordinates(9486): Logged in user auth0|5ece2f3a0e2dbf0cdabcb4a7
08-06 13:47:17.695: D/SecureCredentialsManager(9486): Trying to encrypt the given data using the private key.
08-06 13:47:17.695: D/SecureCredentialsManager(9486): --------- beginning of crash
08-06 13:47:17.723: E/AndroidRuntime(9486): FATAL EXCEPTION: OkHttp Dispatcher
08-06 13:47:17.723: E/AndroidRuntime(9486): Process: no.entur.abt.android.travellerapp.teamdev, PID: 9486
08-06 13:47:17.723: E/AndroidRuntime(9486): java.lang.NullPointerException: invalid null input
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:559)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:526)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:485)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at java.security.KeyStore.getEntry(KeyStore.java:1560)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat(CryptoUtil.java:204)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.authentication.storage.CryptoUtil.getRSAKeyEntry(CryptoUtil.java:98)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.authentication.storage.CryptoUtil.RSAEncrypt(CryptoUtil.java:308)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.authentication.storage.CryptoUtil.getAESKey(CryptoUtil.java:370)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.authentication.storage.CryptoUtil.encrypt(CryptoUtil.java:451)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.authentication.storage.SecureCredentialsManager.saveCredentials(SecureCredentialsManager.java:154)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at no.entur.abt.android.common.support.login.UserCoordinates.postLogin(UserCoordinates.java:250)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at no.entur.abt.android.common.support.login.LoginActivity$1.onSuccess(LoginActivity.java:73)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.provider.OAuthManager$2$1.onSuccess(OAuthManager.java:202)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.provider.OAuthManager$2$1.onSuccess(OAuthManager.java:198)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.provider.OAuthManager$3.onSuccess(OAuthManager.java:251)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.provider.OAuthManager$3.onSuccess(OAuthManager.java:229)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.provider.SignatureVerifier$1.onSuccess(SignatureVerifier.java:65)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.provider.SignatureVerifier$1.onSuccess(SignatureVerifier.java:59)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.request.internal.BaseRequest.postOnSuccess(BaseRequest.java:94)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:80)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-06 13:47:17.723: E/AndroidRuntime(9486): 	at java.lang.Thread.run(Thread.java:764)
```
Please email thomas.skjolberg@gmail.com for a full dump (logs, video etc). 

### What was the expected behavior?
Key should be saved
### Environment
Android api level 27, pixel 2 emulator, in testlab. 

The same code works for other api levels and devices.

**Comment by skjolber** [comment] 2021-09-06 11:01
@lbalmaceda No. Are you running some other "real device" testing by the way? I've spent quite a lot of time making automated tests pass the login screen, it that something that could go into a corresponding test artifact for this library?

**Comment by lbalmaceda** [comment] 2021-09-10 11:13
@skjolber I just have my phone (Pixel 2) running the latest Android, that's why I suggested testing this Android 27 issue on an emulator instead. I don't see any problems adding integration tests as long as what's tested is the SDK / sample app and not the Universal Login. I think that our CI provider (CircleCI) doesn't support running emulators. We would need to look into a service like Browserstack or run these locally. But I'm always open to review a PR.

**Comment by lbalmaceda** [comment] 2021-09-10 14:47
Also, can you please share a snippet with the code that fails, or at least a list of steps/events I should call from my side to reproduce this. Thanks

**Comment by lbalmaceda** [comment] 2021-09-10 15:30
Since the title mentions "NPE when saving credentials" and based on the sample app included with the SDK, I only added a method to save the credentials to a `SecureCredentialsManager` (your logs mention that class). I couldn't reproduce this using the Pixel 2 emulator running Android 27. If you can share some steps, please.
https://user-images.githubusercontent.com/3900123/132877659-45c4a8f3-5b7a-4ed8-b519-9c4907fd46c5.mp4

**Comment by skjolber** [comment] 2021-09-22 11:59
@lbalmaceda I'm not able to reproduce the Pixel 2 problem again. Our code just passes the object through (reading the access-token), so can't see we're doing something wrong. I think that the error might be triggered by bad network. Feel free to close this issue, will just reopen if happens again. 

We're are running testlab from CircleCI by the way. Just use a big instance to build apps and then a small to run them.

**Comment by lbalmaceda** [comment] 2021-09-27 17:06
Re-reading the stack you posted originally, I understand that the error comes from the `com.auth0.android.authentication.storage.CryptoUtil.getKeyEntryCompat` method. In that method, the only line that can throw that NPE is [the last one that creates a KeyEntry](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/CryptoUtil.java#L228.
). You can reproduce that passing `null` in either (or both) params:

```java
// throws: java.lang.NullPointerException: invalid null input
new KeyStore.PrivateKeyEntry(null, null);
```

Checking the code above that line, I see both values that are fed into the constructor are null-checked [here](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/CryptoUtil.java#L220) and [here](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/CryptoUtil.java#L225), so it's not possible for that line to be causing an NPE. Unless of course, the creation of a `Certificate` array results in a null value, which doesn't make sense.


> I think that the error might be triggered by bad network. 

If this is because of a timeout, I'd expect the stack trace to show a bigger time difference but between the "has logged in" debug message and the exception the time diff is minimal. 
![image](https://user-images.githubusercontent.com/3900123/134953277-0e268d59-9169-4538-a10a-008ba254d02b.png).

If this is a "no network available" and immediate failure of the request, that could point to bad handling of error responses from within the SDK (our side). But you just logged in, and you were saving credentials. The manager class doesn't make any requests in the attempt to [save credentials](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt#L133). Unless the exception is totally unrelated to the use of the credentials manager.

**Comment by skjolber** [comment] 2021-09-28 08:26
Looking closer, I can't find any holes either. `getRSAKeyEntry` is an argument-free method, so it is not like we could have messed up on our side either.

As testlab var having problems that day, I guess it is fair to blame this on them / corrupted platform.

**Comment by lbalmaceda** [comment] 2021-09-29 10:10
Alright! I'll close this now but if something similar comes up again comment with more context and I'll re-open. Thanks for raising this.

**Closed by lbalmaceda** 2021-09-29 10:10 UTC
Labels: waiting for customer
