### ISSUE TITLE
Add Ephemeral Session support to Android

### ISSUE THREAD

**Issue by tomhusson-toast** [auth0/Auth0.Android#596] opened 2022-07-12 14:20 UTC
### Describe the problem

After logging in using the bot protection fallback described [here ](https://auth0.com/docs/secure/attack-protection/bot-detection/bot-detection-native-apps#auth0-android-example), then logging out, subsequent attempts to use bot protection fail. Clearing cookies inside the custom tab unblocks this so it seems cookie related. On iOS the '.useEphemeralSession()' setting seems to accomplish this. 

<img width="633" alt="Screen Shot 2022-07-12 at 10 12 53 AM" src="https://user-images.githubusercontent.com/90268841/178510803-82ed8c6c-b90b-4947-82b2-9f5da5117275.png">

### What was the expected behavior?

Bot protection should continue to work after login / logout cycle

### Reproduction
1. Login via bot protection
2. Logout user
3. Attempt to login again via bot protection
4. "Not Found" response

### Environment
com.auth0.android:auth0:2.8.0

**Comment by poovamraj** [comment] 2022-07-19 12:21
Hi @tomhusson-toast we currently do not have plans on doing as iOS provides explicit support for this where as Android doesn't. We would rather like to address the issue on why it is not working on the current configuration as it should work. I tried to reproduce this issue and was not able to. Will it be possible for you to provide us with a minimal app that is able to reproduce this issue?

**Comment by poovamraj** [comment] 2022-07-21 17:54
Hi @tomhusson-toast since ephermal sessions is not directly supported by Chrome Custom Tabs and the only other way for us is to use [Incognito Custom Tabs](https://groups.google.com/a/chromium.org/g/chromium-reviews/c/d1901HSe8nc) which is also behind feature flag and doesn't provide the exact use case we need. We will be closing this issue. Please feel to reach out to us if you need any other help

**Closed by poovamraj** 2022-07-21 17:54 UTC

**Comment by PGMacDesign** [comment] 2022-10-25 20:54
Hi all. 
We are facing a related issue where we do actually need this `ephemeral session` concept added so that we can mirror the logic defined in ios [here](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md#bot-detection). The problem we are facing is that it maintains a session token and the person that just logs out `user1` who then tries to login with a different user `user2` automatically gets logged in as `user1`. 

If this won't be implemented on Android, how can we mimic this ephemeral concept so that the user doesn't stay perma-logged in when they should not be?

**Comment by PGMacDesign** [comment] 2022-10-25 21:32
Looks like the workaround is outlined here -->  https://github.com/auth0/Auth0.Android/issues/531

**Comment by pmathew92** [comment] 2026-04-21 05:36
Hi everyone, we have released a new beta for the next major version [v4](https://github.com/auth0/Auth0.Android/releases/tag/4.0.0-beta.0) of the Auth0.Android SDK which contains the support for ephemeral session . Please try it out and let us know
